<template><div><h1 id="observability" tabindex="-1"><a class="header-anchor" href="#observability"><span>Observability</span></a></h1>
<p>The KurrentDB gRPC clients are designed with observability in mind, offering
support for OpenTelemetry. This integration provides a set of distributed
traces, enabling developers to gain deeper insights into their system.</p>
<h2 id="required-packages" tabindex="-1"><a class="header-anchor" href="#required-packages"><span>Required packages</span></a></h2>
<p>The KurrentDB C# client includes OpenTelemetry support by default.</p>
<h2 id="instrumentation" tabindex="-1"><a class="header-anchor" href="#instrumentation"><span>Instrumentation</span></a></h2>
<p>To emit trace data, you must first install and use the dedicated package, as instructed in the
<RouteLink to="/api/observability.html#required-packages">Required Packages</RouteLink> section, if provided. This package
includes the necessary instrumentation that needs to be registered with the client.</p>
<div class="language-cs line-numbers-mode" data-highlighter="shiki" data-ext="cs" data-title="cs" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">var</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75"> host</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2"> =</span><span style="--shiki-light:#383A42;--shiki-dark:#E5C07B"> Host</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">CreateDefaultBuilder</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">()</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  .</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">ConfigureServices</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">    (</span><span style="--shiki-light:#383A42;--shiki-dark:#E5C07B">_</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">, </span><span style="--shiki-light:#383A42;--shiki-dark:#E5C07B">services</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">) => {</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#E5C07B">      services</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">AddSingleton</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(new </span><span style="--shiki-light:#C18401;--shiki-dark:#E5C07B">ActivitySource</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">serviceName</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">));</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">      services</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">        .</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">AddOpenTelemetry</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">()</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">        .</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">ConfigureResource</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#383A42;--shiki-dark:#E5C07B">builder</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> => </span><span style="--shiki-light:#383A42;--shiki-dark:#E5C07B">builder</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">AddService</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">serviceName</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">))</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">        .</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">WithTracing</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#383A42;--shiki-dark:#E5C07B">tracerProvider</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> => {</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">          tracerProviderBuilder</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">            .</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">AddEventStoreClientInstrumentation</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">();</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">        });</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">    }</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  )</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  .</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Build</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">();</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="traces" tabindex="-1"><a class="header-anchor" href="#traces"><span>Traces</span></a></h2>
<p>Traces provide a clear picture of how operations are carried out in a
distributed system, making it easier to maintain and enhance the system over
time. Traces from the clients can be exported to any compatible collector that
supports the OpenTelemetry protocol (OTLP).</p>
<p>In order for the client to emit traces, you need to need to enable
instrumentation as described in
<RouteLink to="/api/observability.html#instrumentation">Instrumentation</RouteLink>.</p>
<p>For more guidance on setting up and utilizing tracing, refer to the
<a href="https://opentelemetry.io/" target="_blank" rel="noopener noreferrer">OpenTelemetry</a> documentation.</p>
<p>An example of a trace is shown below:</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Activity.TraceId:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">            8da04787239dbb85c1f9c6fba1b1f0d6</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Activity.SpanId:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">             4352ec4a66a20b95</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Activity.TraceFlags:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">         Recorded</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Activity.ActivitySourceName:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> kurrentdb</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Activity.DisplayName:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">        streams.append</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Activity.Kind:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">               Client</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Activity.StartTime:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">          2024-05-29T06:50:41.2519016Z</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Activity.Duration:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">           00:00:00.1500707</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Activity.Tags:</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">    db.kurrentdb.stream:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> d7caa2a5-1e19-4108-9541-58d5fba02d42</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">    server.address:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> localhost</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">    server.port:</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 2113</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">    db.system:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> kurrentdb</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">    db.operation:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> streams.append</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">StatusCode:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Ok</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Resource</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> associated</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> with</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Activity:</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">    service.name:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> sample</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">    service.instance.id:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 7316ef20-c354-4e64-97da-c1b99c2c28b0</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">    telemetry.sdk.name:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> opentelemetry</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">    telemetry.sdk.language:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> dotnet</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">    telemetry.sdk.version:</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 1.8.1</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>In this case, the trace is for an append operation on a stream. The trace
includes the trace ID, span ID, trace flags, activity source name, display name,
kind, start time, duration, tags, status code, and resource associated with the
activity.</p>
<div class="hint-container note">
<p class="hint-container-title">Note</p>
<p>The structure of the trace may vary depending on the client and the operation
being performed but will generally include the same information.</p>
</div>
<h2 id="exporting-traces" tabindex="-1"><a class="header-anchor" href="#exporting-traces"><span>Exporting traces</span></a></h2>
<p>You can set up various exporters to send traces to different destinations.
Additionally, you have the option to export these traces to a collector of your
choice, such as <a href="https://www.jaegertracing.io/" target="_blank" rel="noopener noreferrer">Jaeger</a> or <a href="https://datalust.co/seq" target="_blank" rel="noopener noreferrer">Seq</a>.</p>
<p>For instance, if you choose to use Jaeger as your backend of choice, you can
view your traces in the Jaeger UI, which provides a powerful interface for
querying and visualizing your trace data.</p>
<p>The code snippets below demonstrate how to set up one or more exporters for each
client:</p>
<div class="language-cs line-numbers-mode" data-highlighter="shiki" data-ext="cs" data-title="cs" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">var</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75"> host</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2"> =</span><span style="--shiki-light:#383A42;--shiki-dark:#E5C07B"> Host</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">CreateDefaultBuilder</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">()</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  .</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">ConfigureServices</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">    (</span><span style="--shiki-light:#383A42;--shiki-dark:#E5C07B">_</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">, </span><span style="--shiki-light:#383A42;--shiki-dark:#E5C07B">services</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">) => {</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#E5C07B">      services</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">AddSingleton</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(new </span><span style="--shiki-light:#C18401;--shiki-dark:#E5C07B">ActivitySource</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">serviceName</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">));</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">      services</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">        .</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">AddOpenTelemetry</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">()</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">        .</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">ConfigureResource</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#383A42;--shiki-dark:#E5C07B">builder</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> => </span><span style="--shiki-light:#383A42;--shiki-dark:#E5C07B">builder</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">AddService</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">serviceName</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">))</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">        .</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">WithTracing</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#383A42;--shiki-dark:#E5C07B">tracerProvider</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> => {</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#E06C75">          tracerProviderBuilder</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">            .</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">AddEventStoreClientInstrumentation</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">()</span></span>
<span class="line highlighted"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">            .</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">AddConsoleExporter</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">()</span></span>
<span class="line highlighted"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">            .</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">AddJaegerExporter</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span></span>
<span class="line highlighted"><span style="--shiki-light:#383A42;--shiki-dark:#E5C07B">              options</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> => {</span></span>
<span class="line highlighted"><span style="--shiki-light:#383A42;--shiki-dark:#E5C07B">                options</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#383A42;--shiki-dark:#E5C07B">Endpoint</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2"> =</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> new </span><span style="--shiki-light:#C18401;--shiki-dark:#E5C07B">Uri</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"http://localhost:4317"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">);</span></span>
<span class="line highlighted"><span style="--shiki-light:#383A42;--shiki-dark:#E5C07B">                options</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#383A42;--shiki-dark:#E5C07B">Protocol</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2"> =</span><span style="--shiki-light:#383A42;--shiki-dark:#E5C07B"> JaegerExportProtocol</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">.</span><span style="--shiki-light:#383A42;--shiki-dark:#E5C07B">UdpCompactThrift</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">;</span></span>
<span class="line highlighted"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">              }</span></span>
<span class="line highlighted"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">            );</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">        });</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">    }</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  )</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  .</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Build</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">();</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>For more details on configuring exporters for specific programming languages,
refer to the <a href="https://opentelemetry.io/docs/languages/" target="_blank" rel="noopener noreferrer">OpenTelemetry</a>
documentation.</p>
</div></template>


