name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  ci:
    name: Tests
    uses: ./.github/workflows/base.yml
    strategy:
      fail-fast: false
      matrix:
        test: [ Streams, PersistentSubscriptions, Operations, UserManagement, ProjectionManagement, Security, Misc ]
        runtime: [ previous-lts, lts, ci ]
    with:
      test: ${{ matrix.test }}
      runtime: ${{ matrix.runtime }}
    secrets: inherit
